[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["cd packages/web && bunx vite build"]

[start]
cmd = "cd packages/web && bun src/server.ts"
